use crate::ast::{Expr, Function, Param};

grammar;

match {
  r"\s*" => { },
  _
}

pub Func: Function = {
  "def" <name:Ident> "(" <params:Params> ")" "->" <return_type:Ident> <body:Expr> "end" => Function {
    name,
    params,
    return_type,
    body,
  }
};

Params: Vec<Param> = {
  <mut v:(<Param> ",")*> <last:Param?> => {
    match last {
      None => v,
      Some(p) => { v.push(p); v }
    }
  }
};

Param: Param = {
  <name:Ident> ":" <ty:Ident> => Param { name, ty }
};

Expr: Expr = {
  <lhs:Ident> "+" <rhs:Ident> => Expr::Add(Box::new(Expr::Ident(lhs)), Box::new(Expr::Ident(rhs))),
  <name:Ident> => Expr::Ident(name),
};

Ident: String = <s:r"[A-Za-z_][A-Za-z0-9_]*"> => s.to_string();
